### ISSUE TITLE
Bullet AC IP67 (nickname AP 5) not showing up on local network

### ISSUE THREAD

**Issue by austinlake04** [SC-Robotics-2021/SCR_2022-23#7]
model: Bullet AC IP67
mac address: 78:45:58:a2:44:40
nickname: AP 5
username: `ubnt_bulletac`
password: `rpi_rover123`

This bullet does not appear on the network. Also, the documentation shown [here](https://github.com/SC-Robotics-2021/SCR_2022-23/blob/master/Telecom/TELECOM.md) is slightly off. From what I am seeing on the network, AP 2 (mac address 78:45:58:a2:45:02) appears on the network as 192.168.1.27 rather than 192.168.1.27. An example network scan is showing below with the following command: `sudo nmap -sN 192.168.1.0/24`

<img width="513" alt="Screenshot 2022-12-22 at 17 05 12" src="https://user-images.githubusercontent.com/53884490/209251035-1be8139a-eadd-447c-b974-acafc6afab05.png">

**Comment by wluxie** [comment]
Yea, I think the documentation is slightly outdated. We'll be back on Monday to tidy it up and update everything. 

We couldn't get the Bullet AC to work as a 5Ghz antenna (AP 5), so that's why we switched to the RocketM5. And I supposed that's why we needed you to help us out with that or take a look.

Thank you, we'll check it out!
